package com.cg.ibs.investment.ui;

public enum Menu {
	VIEW_MY_INVESTMENT, VIEW_GOLD_PRICE, VIEW_SILVER_PRICE,VIEW_MF_PLANS,BUY_GOLD,SELL_GOLD,BUY_SILVER,SELL_SILVER,INVEST_MF_PLAN,WITHDRAW_MF_PLAN,QUIT

}
